[versions]
agp = "8.11.1"
kotlin = "2.2.0"
ktx = "1.16.0"
activity = "1.10.1"
recyclerview = "1.4.0"
room = "2.7.2"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
lifecycle = "2.9.2"
navigation = "2.9.2"
car-app = "1.7.0"
gson = "2.13.1"
gms-location = "21.3.0"
kotlinx = "1.10.2"
serialization = "1.9.0"
composeBom = "2025.07.00"
aboutlibraries = "12.2.4"
paris = "2.0.2"
leakcanary = "2.14"
google-services = "4.4.3"
firebase-crashlytics = "3.0.4"
retrofit = "3.0.0"
okhttp3 = "5.1.0"
window = "1.4.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-car-app = {group = "androidx.car.app", name = "app", version.ref = "car-app"}
androidx-car-app-automotive = {group = "androidx.car.app", name = "app-automotive", version.ref = "car-app"}
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group="androidx.activity", name = "activity-compose", version.ref = "activity"}
androidx-compose-ui = { group="androidx.compose.ui", name = "ui" }
androidx-compose-material = { group="androidx.compose.material", name = "material" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle"}
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3"}

google-gson = { group = "com.google.code.gson", name ="gson", version.ref = "gson" }
google-gms-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "gms-location"}

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx"}
kotlinx-coroutines-play-services = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutlibraries" }
airbnb-paris = { group = "com.airbnb.android", name = "paris", version.ref = "paris"}
github-egm96 = { group = "com.github.matthiaszimmermann", name = "EGM96", version = "master-SNAPSHOT"}
github-scrollbar = {group = "com.github.nanihadesuka", name = "LazyColumnScrollbar", version = "2.2.0"}

squareup-leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref= "kotlin" }
kotlinSerialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries"}
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services"}
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }