[versions]
agp = "8.3.2"
kotlin = "2.0.0" # Can't bump Kotlin version yet due to synthetics
ktx = "1.13.1"
activity = "1.9.0"
fragment-ktx = "1.7.1"
recyclerview = "1.3.2"
room = "2.6.1"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
lifecycle = "2.8.1"
navigation = "2.8.0-beta02"
car-app = "1.7.0-alpha02"
gson = "2.10.1"
gms-location = "21.3.0" # Newer version requires Kotlin 1.9, see above
kotlinx = "1.7.3"
serialization = "1.7.0"
compose = "1.6.7"
jakara-mail = "2.0.0"
aboutlibraries = "10.6.1"
aboutlibraries-plugin = "10.9.2"
paris = "2.0.0"
leakcanary = "2.8.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-car-app = {group = "androidx.car.app", name = "app", version.ref = "car-app"}
androidx-car-app-automotive = {group = "androidx.car.app", name = "app-automotive", version.ref = "car-app"}
androidx-activity-compose = { group="androidx.activity", name = "activity-compose", version.ref = "activity"}
androidx-compose-ui = { group="androidx.compose.ui", name = "ui", version.ref = "compose"}
androidx-compose-material = { group="androidx.compose.material", name = "material", version.ref = "compose"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle"}
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}

google-gson = { group = "com.google.code.gson", name ="gson", version.ref = "gson" }
google-gms-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "gms-location"}

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx"}
kotlinx-coroutines-play-services = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
jakarta-mail = { group = "org.eclipse.angus", name = "jakarta.mail", version.ref = "jakara-mail"}
aboutlibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries"}
airbnb-paris = { group = "com.airbnb.android", name = "paris", version.ref = "paris"}
github-egm96 = { group = "com.github.matthiaszimmermann", name = "EGM96", version = "master-SNAPSHOT"}

squareup-leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref= "kotlin" }
kotlinSerialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries-plugin"}
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }